- id: '1706033557076'
  alias: 'Washer started '
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 8ac6ee427c35c0903d2a3123390c032d
    entity_id: 9cf0e4aecfc63be529ca4e824679fafc
    domain: sensor
    above: 50
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.washerrunning
    data: {}
  mode: single
- id: '1706033863099'
  alias: Washer Finished
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 8ac6ee427c35c0903d2a3123390c032d
    entity_id: 9cf0e4aecfc63be529ca4e824679fafc
    domain: sensor
    below: 3.9
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.washerrunning
    state: 'on'
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - if:
    - type: is_power
      condition: device
      device_id: 8ac6ee427c35c0903d2a3123390c032d
      entity_id: 9cf0e4aecfc63be529ca4e824679fafc
      domain: sensor
      below: 40
    then:
    - service: tts.speak
      metadata: {}
      data:
        cache: false
        media_player_entity_id: media_player.kitchen_speaker
        message: The wash has completed
      target:
        entity_id: tts.google_en_com
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.washerrunning
      data: {}
  mode: single
