
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: rest
    name: postvalues
    resource_template: >-
        http://ha.rippofunk.com/record.php?sensor_value={{states('sensor.powermeter_voltage') }}&sensor_name=voltage
    value_template: '1'  
    scan_interval: 60 