esphome:
  name: smartplug1
  friendly_name: smartPlug1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LdreSHZ2o95Y16ZcwKn8aFtmNCV4a9lBXrZPvo02AzA="

ota:
  password: "92a31f2c165267da7ceb1be02d5140bd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartplug1 Fallback Hotspot"
    password: "xIlKP9sMfFZd"

captive_portal:
    


uart:
  rx_pin: 14
  tx_pin: 12
  baud_rate: 9600

modbus:

sensor:
  - platform: pzemac
    current:
      name: "smartplug1 Current"
      filters:
      - calibrate_linear:
          - 0 -> 0
          - 72.7 -> 12.0
    voltage:
      name: "smartplug1 Voltage"
    energy:
      name: "smartplug1 Energy"
    power:
      name: "smartplug1 Power"
      filters:
      - calibrate_linear:
          - 0 -> 0
          - 8300 -> 1333
    frequency:
      name: "smartplug1 Frequency"
    power_factor:
      name: "smartplug1 Power Factor"
    update_interval: 1s